# Generated by Django 3.2 on 2021-04-16 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memo_id', models.AutoField(primary_key=True, serialize=False)),
                ('memo_title', models.CharField(max_length=250)),
                ('memo_content', models.TextField()),
                ('memo_date', models.DateTimeField(auto_now=True)),
                ('memo_img', models.CharField(max_length=250, null=True)),
                ('article_id', models.ForeignKey(default='bookshelf', on_delete=django.db.models.deletion.SET_DEFAULT, to='book.book_article')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
