# Generated by Django 3.2 on 2021-04-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communication_user_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='user_pk',
            new_name='user_id',
        ),
    ]
