# Generated by Django 3.2 on 2021-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication_category',
            field=models.IntegerField(),
        ),
    ]
