# Generated by Django 3.2 on 2021-04-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_content', models.TextField()),
                ('book_writter', models.CharField(max_length=50)),
                ('book_intro', models.TextField()),
                ('book_like', models.IntegerField(default=0)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_img', models.CharField(max_length=250)),
                ('book_subscribe', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=250)),
                ('article_content', models.TextField()),
                ('article_img', models.CharField(max_length=250)),
                ('article_date', models.DateTimeField(auto_now=True)),
                ('article_views', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book_article')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
