# Generated by Django 3.2 on 2021-04-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(default='bookshelf', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.profile'),
        ),
    ]
