# Generated by Django 3.2 on 2021-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_writter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book_article',
            name='article_img',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
