# Generated by Django 3.2 on 2021-04-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_signbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_content',
        ),
    ]
