# Generated by Django 3.2 on 2021-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_info',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Member_Profile',
        ),
    ]
